site_name: Documentação Guia de Acessiblidade Digital

nav:
  - Página Inicial: index.md
  - Guia de Acessiblidade:
      - Sobre: guia_acessibilidade/sobre.md
      - Gestão de Projetos: guia_acessibilidade/guia_gestao.md
      - Desenvolvimento: guia_acessibilidade/guia_desenvolvimento.md
      - Design: guia_acessibilidade/guia_design.md
      - Conteúdo: guia_acessibilidade/guia_conteudo.md
  - Fundamentos de UX:
      - UX: ux/ux.md
      - Personas: ux/personas.md
      - Jornadas: ux/jornadas.md
      - Blueprint: ux/blueprint.md
      - Canvas: ux/canvas.md
      - Design Empático: ux/design_empatico.md
      - Heurísticas de Nielsen: ux/heuristicas_nielsen.md
  - Resultado Final: resultado/resultado.md
  - Referências e Ferramentas: referencias/referencias.md
  - Histórico de Versões: historico/historico.md
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      clickable_checkbox: true

extra_css:
  - css/custom.css

extra_javascript:
  - js/progress.js